language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "dev"
sudo: false

env:
  global: 
    - COVERAGE=1
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
    - AUTOMATED_TESTING=1
    - HARNESS_OPTIONS=c
    - HARNESS_TIMER=1


before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --always-upgrade-modules
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install --deps --update-prereqs
  - cpan-install --coverage

after_install:
  - make realclean

before_script:
  - coverage-setup

script:
  - prove -lrsv t

after_success:
  - coverage-report
